import {
  CreditCard,
  CircleDollarSign,
  TrendingUp,
  Lock,
  PiggyBank,
  BellRing,
  CalendarDays,
  Mailbox,
  Banknote,
  Landmark,
  BadgeDollarSign,
  Receipt,
  SaveAll,
  RotateCcw,
  Plus,
  Wallet,
  Trash2,
} from "lucide-react";

export const Icons = {
  card: CreditCard,
  cash: CircleDollarSign,
  investment: TrendingUp,
  compromised: Lock,
  freeinvest: PiggyBank,
  reminder: BellRing,
  calendar: CalendarDays,
  mailbox: Mailbox,
  currency: Banknote,
  accounts: Landmark,
  fixincome: BadgeDollarSign,
  fixexpense: Receipt,
  save: SaveAll,
  reset: RotateCcw,
  add: Plus,
  wallet: Wallet,
  trash: Trash2,
};